Vagrant.configure("2") do |config|
	config.vm.provision "shell", path: "setup.sh"

	config.vm.box = "centos/7"
	config.vm.provider "virtualbox" do |v|
		v.gui = false
	end

	config.vm.define "worker" do |worker|
		worker.vm.network "private_network", type: "dhcp"
		worker.vm.hostname = "worker"
		worker.vm.provider "virtualbox" do |v|
			v.cpus = 2
			v.name = "worker"
			v.memory = 4096

		end
	end

end


