Vagrant.configure("2") do |config|
	#config.vm.box = "ubuntu/trusty64"
	config.vm.box = "centos/7"
	config.vm.provider "virtualbox" do |v|
		v.gui = false
		v.name = "k8s"
		v.cpus = 2
		v.memory = 4096
	end
	config.vm.provision "shell", path: "setup.sh"
end


