Vagrant.configure("2") do |config|
	config.vm.provision "shell", path: "setup.sh"

	config.vm.box = "centos/7"
	config.vm.provider "virtualbox" do |v|
		v.gui = false
	end

	config.vm.define "k8s-master" do |master|
		master.vm.network "private_network", type: "dhcp"
		master.vm.hostname = "k8s-master"
		master.vm.provider "virtualbox" do |v|
			v.cpus = 1
			v.name = "k8s-master"
			v.memory = 1024
		end
	end

	config.vm.define "k8s-worker" do |worker|
		worker.vm.network "private_network", type: "dhcp"
		worker.vm.hostname = "k8s-worker"
		worker.vm.provider "virtualbox" do |v|
			v.cpus = 2
			v.name = "k8s-worker"
			v.memory = 2048

		end
	end

end


